/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bwea.attendancesystem;

import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Acer
 */
public class ChartTest extends javax.swing.JFrame {

    /**
     * Creates new form ChartTest
     */
    public ChartTest() {
        initComponents();
        
  
    // Create dataset  
    DefaultCategoryDataset dataset = createDataset();  
    // Create chart  
    JFreeChart chart = ChartFactory.createLineChart(  
        "Daily Attendance", // Chart title  
        "Day", // X-Axis Label  
        "Number of Students", // Y-Axis Label  
        dataset  
        );  
  
    ChartPanel panel = new ChartPanel(chart);  
    setContentPane(panel);  
    }
    
      private DefaultCategoryDataset createDataset() {  
  
          //SQL statement
          //SELECT DAYOFWEEK(DATE(Datein)), COUNT(`Registration No`) FROM  attendance  GROUP BY DAYOFWEEK(DATE(Datein));
          
          
    String series1 = "Count";  
    
  
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
  
    dataset.addValue(55, series1, "Monday");  
    dataset.addValue(100, series1, "Tuesday");  
    dataset.addValue(5, series1, "Wednesday");  
    dataset.addValue(80, series1, "Thursday");  
    dataset.addValue(90, series1, "Friday");  
    dataset.addValue(10, series1, "Saturday");  
    dataset.addValue(50, series1, "Sunday");  
  
    
  
    return dataset;  
  }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {  
    SwingUtilities.invokeLater(() -> {  
      ChartTest att = new ChartTest();  
      att.setAlwaysOnTop(true);  
      att.pack();  
      att.setSize(600, 400);  
      att.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      att.setVisible(true);  
    });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
